import sqlite3

# Conectar no db local
conn = sqlite3.connect('penal.db')
cursor = conn.cursor()

# Criar tabela
cursor.execute('''
        CREATE TABLE IF NOT EXISTS penal 
        (id INTEGER PRIMARY KEY, 
        crime TEXT  NOT NULL,
        Cod_penal TEXT NOT NULL
        )''')

# Colocando datos na tab
cursor.execute(''' INSERT INTO penal (Crime, Cod_penal)
                VALUES("Homicídio", "Art. 121"),
                ("Homicídio Simples", "Art. 121"),
                ("Homicídio Qualificado", "Art. 121"),
                ("Homicídio Privilegiado", "Art. 121"),
                ("Feminicídio", "Art. 121"),
                ("Participação em Suicídio", "Art. 122"),
                ("Infanticídio", "Art. 123"),
                ("Aborto Provocado pela Gestante ou com seu Consentimento", "Art. 124"),
                ("Aborto Provocado por Terceiro", "Art. 125"),
                ("Aborto sem o Consentimento da Gestante", "Art. 126"),
                ("Aborto Necessário", "Art. 128, Inciso I"),
                ("Aborto no Caso de Gravidez Resultante de Estupro", "Art. 128, Inciso II"),
                ("Lesão Corporal Simples", "Art. 129"),
                ("Lesão Corporal de Natureza Grave", "Art. 129"),
                ("Lesão Corporal Gravíssima", "Art. 129"),
                ("Lesão Corporal Seguida de Morte", "Art. 129"),
                ("Perigo de Contágio Venéreo", "Art. 130"),
                ("Perigo de Contágio de Moléstia Grave", "Art. 131"),
                ("Perigo para a Vida ou Saúde de Outrem", "Art. 132"),
                ("Abandono de Incapaz", "Art. 133"),
                ("Exposição ou Abandono de Recém-Nascido", "Art. 134"),
                ("Omissão de Socorro", "Art. 135"),
                ("Calúnia", "Art. 138"),
                ("Difamação", "Art. 139"),
                ("Injúria", "Art. 140"),
                ("Constrangimento Ilegal", "Art. 146"),
                ("Ameaça", "Art. 147"),
                ("Sequestro e Cárcere Privado", "Art. 148"),
                ("Furto Simples", "Art. 155"),
                ("Furto Qualificado", "Art. 155"),
                ("Roubo Simples", "Art. 157"),
                ("Roubo Qualificado", "Art. 157"),
                ("Extorsão", "Art. 158"),
                ("Dano Simples", "Art. 163"),
                ("Dano Qualificado", "Art. 163"),
                ("Estelionato", "Art. 171"),
                ("Apropriação Indébita Simples", "Art. 168"),
                ("Apropriação Indébita Previdenciária", "Art. 168-A"),
                ("Receptação Simples", "Art. 180"),
                ("Receptação Qualificada", "Art. 180"),
                ("Alteração de Limites", "Art. 161, Inciso I"),
                ("Esbulho Possessório", "Art. 161, Inciso II"),
                ("Destruição ou Danificação de Coisas Alheias", "Art. 161, Inciso III"),
                ("Corrupção Passiva", "Art. 317"),
                ("Peculato", "Art. 312"),
                ("Concussão", "Art. 316"),
                ("Prevaricação", "Art. 319"),
                ("Desacato", "Art. 331"),
                ("Corrupção Ativa", "Art. 333"),
                ("Desobediência", "Art. 330"),
                ("Resistência", "Art. 329"),
                ("Tráfico de Influência", "Art. 332"),
                ("Violência Arbitrária", "Art. 322"),
                ("Falsificação de Moeda", "Art. 289"),
                ("Petrechos de Falsificação", "Art. 291"),
                ("Falsificação de Documento Público", "Art. 297"),
                ("Falsificação de Documento Particular", "Art. 298"),
                ("Falsificação de Selo ou Sinal Público", "Art. 296"),
                ("Falsidade Ideológica", "Art. 299"),
                ("Falsidade de Atestado Médico", "Art. 302"),
                ("Denunciação Caluniosa", "Art. 339"),
                ("Comunicação Falsa de Crime ou Contravenção", "Art. 340"),
                ("Auto-acusação Falsa", "Art. 341"),
                ("Falso Testemunho ou Falsa Perícia", "Art. 342"),
                ("Coação no Curso do Processo", "Art. 344"),
                ("Apologia de Crime ou Criminoso", "Art. 287"),
                ("Incitação ao Crime", "Art. 286"),
                ("Quadrilha ou Bando", "Art. 288"),
                ("Incêndio", "Art. 250"),
                ("Explosão", "Art. 251"),
                ("Inundação", "Art. 254"),
                ("Desabamento ou Desmoronamento", "Art. 256"),
                ("Envenenamento de Água Potável ou Substância Alimentícia ou Medicinal", "Art. 270"),
                ("Estupro de Vulnerável", "Art. 217-A"),
                ("Violação Sexual Mediante Fraude", "Art. 215"),
                ("Assédio Sexual", "Art. 216-A"),
                ("Corrupção de Menores", "Art. 218"),
                ("Satisfação de Lascívia Mediante Presença de Criança ou Adolescente", "Art. 218-A"),
                ("Favorecimento da Prostituição ou Outra Forma de Exploração Sexual de Criança ou Adolescente ou de Vulnerável", "Art. 218-B"),
                ("Bigamia", "Art. 235"),
                ("Induzimento a Erro Essencial e Ocultação de Impedimento", "Art. 236"),
                ("Simulação de Casamento", "Art. 237"),
                ("Registro de Nascimento Inexistente", "Art. 241"),
                ("Parto Suposto e Supressão ou Alteração de Direito Inerente ao Estado Civil de Recém-Nascido", "Art. 242"),
                ("Violação de Direito Autoral", "Art. 184"),
                ("Crimes contra Marcas e Patentes", "Lei nº 9.279/1996"),
                ("Concorrência Desleal", "Art. 195 da Lei nº 9.279/1996"),
                ("Corrupção Eleitoral", "Art. 299 do Código Eleitoral"),
                ("Captação Ilícita de Sufrágio", "Art. 41-A da Lei nº 9.504/1997"),
                ("Invasão de Dispositivo Informático", "Art. 154-A"),
                ("Interrupção ou Perturbação de Serviço Telegráfico, Radiotelegráfico ou Telefônico", "Art. 266"),
                ("Falsidade Ideológica em Meio Eletrônico", "Art. 299, Parágrafo Único"),
                ("Homicídio Culposo no Trânsito", "Art. 302 do Código de Trânsito Brasileiro"),
                ("Lesão Corporal Culposa no Trânsito", "Art. 303 do Código de Trânsito Brasileiro"),
                ("Sonegação Fiscal", "Lei nº 8.137/1990"),
                ("Crimes Contra o Meio Ambiente", "Lei nº 9.605/1998"),
                ("Lavagem de Dinheiro", "Lei nº 9.613/1998"),
                ("Organização Criminosa", "Lei nº 12.850/2013"),
                ("Tráfico de Drogas", "Lei nº 11.343/2006"),
                ("Associação para o Tráfico", "Lei nº 11.343/2006"),
                ("Financiamento do Tráfico", "Lei nº 11.343/2006"),
                ("Corrupção de Funcionário Público", "Art. 317"),
                ("Desvio de Verba Pública", "Art. 312"),
                ("Fraude em Licitação", "Lei nº 8.666/1993"),
                ("Tráfico de Pessoas", "Lei nº 13.344/2016"),
                ("Crimes Contra o Consumidor", "Lei nº 8.078/1990"),
                ("Crimes Contra a Ordem Econômica", "Lei nº 8.137/1990"),
                ("Crimes Contra o Sistema Financeiro Nacional", "Lei nº 7.492/1986"),
                ("Crimes Contra as Relações de Consumo", "Lei nº 8.137/1990"),
                ("Crimes Contra a Propriedade Imaterial", "Lei nº 9.279/1996"),
                ("Crimes de Responsabilidade", "Decreto-Lei nº 201/1967"),
                ("Crimes de Tortura", "Lei nº 9.455/1997"),
                ("Crimes Hediondos", "Lei nº 8.072/1990"),
                ("Tráfico de Órgãos", "Lei nº 9.434/1997"),
                ("Violação de Sepultura", "Art. 210"),
                ("Destruição de Cadáver", "Art. 211"),
                ("Crimes de Genocídio", "Lei nº 2.889)''')  

# Fechando a comunicação
conn.commit()
conn.close()